// Code generated by Kitex v0.9.1. DO NOT EDIT.

package activityservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	activity "seckill_system/srv-activity/kitex_gen/activity"
	product "seckill_system/srv-activity/kitex_gen/product"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetActivities": kitex.NewMethodInfo(
		getActivitiesHandler,
		newActivityServiceGetActivitiesArgs,
		newActivityServiceGetActivitiesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetActivityInfo": kitex.NewMethodInfo(
		getActivityInfoHandler,
		newActivityServiceGetActivityInfoArgs,
		newActivityServiceGetActivityInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	activityServiceServiceInfo                = NewServiceInfo()
	activityServiceServiceInfoForClient       = NewServiceInfoForClient()
	activityServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return activityServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return activityServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return activityServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ActivityService"
	handlerType := (*activity.ActivityService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "activity",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func getActivitiesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*activity.ActivityServiceGetActivitiesArgs)
	realResult := result.(*activity.ActivityServiceGetActivitiesResult)
	success, err := handler.(activity.ActivityService).GetActivities(ctx, realArg.A)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newActivityServiceGetActivitiesArgs() interface{} {
	return activity.NewActivityServiceGetActivitiesArgs()
}

func newActivityServiceGetActivitiesResult() interface{} {
	return activity.NewActivityServiceGetActivitiesResult()
}

func getActivityInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*activity.ActivityServiceGetActivityInfoArgs)
	realResult := result.(*activity.ActivityServiceGetActivityInfoResult)
	success, err := handler.(activity.ActivityService).GetActivityInfo(ctx, realArg.A)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newActivityServiceGetActivityInfoArgs() interface{} {
	return activity.NewActivityServiceGetActivityInfoArgs()
}

func newActivityServiceGetActivityInfoResult() interface{} {
	return activity.NewActivityServiceGetActivityInfoResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetActivities(ctx context.Context, a *activity.Activity) (r []*product.Product, err error) {
	var _args activity.ActivityServiceGetActivitiesArgs
	_args.A = a
	var _result activity.ActivityServiceGetActivitiesResult
	if err = p.c.Call(ctx, "GetActivities", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetActivityInfo(ctx context.Context, a *activity.Activity) (r *activity.Activity, err error) {
	var _args activity.ActivityServiceGetActivityInfoArgs
	_args.A = a
	var _result activity.ActivityServiceGetActivityInfoResult
	if err = p.c.Call(ctx, "GetActivityInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
