// Code generated by Kitex v0.9.1. DO NOT EDIT.
package activityservice

import (
	server "github.com/cloudwego/kitex/server"
	activity "seckill_system/srv-activity/kitex_gen/activity"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler activity.ActivityService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler activity.ActivityService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
