// Code generated by Kitex v0.9.1. DO NOT EDIT.

package orderservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	order "seckill_system/srv-order/kitex_gen/order"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateOrder": kitex.NewMethodInfo(
		createOrderHandler,
		newOrderServiceCreateOrderArgs,
		newOrderServiceCreateOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteOrder": kitex.NewMethodInfo(
		deleteOrderHandler,
		newOrderServiceDeleteOrderArgs,
		newOrderServiceDeleteOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetOrderStatus": kitex.NewMethodInfo(
		getOrderStatusHandler,
		newOrderServiceGetOrderStatusArgs,
		newOrderServiceGetOrderStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	orderServiceServiceInfo                = NewServiceInfo()
	orderServiceServiceInfoForClient       = NewServiceInfoForClient()
	orderServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return orderServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return orderServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return orderServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "OrderService"
	handlerType := (*order.OrderService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "order",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func createOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceCreateOrderArgs)
	realResult := result.(*order.OrderServiceCreateOrderResult)
	success, err := handler.(order.OrderService).CreateOrder(ctx, realArg.O)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceCreateOrderArgs() interface{} {
	return order.NewOrderServiceCreateOrderArgs()
}

func newOrderServiceCreateOrderResult() interface{} {
	return order.NewOrderServiceCreateOrderResult()
}

func deleteOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceDeleteOrderArgs)
	realResult := result.(*order.OrderServiceDeleteOrderResult)
	success, err := handler.(order.OrderService).DeleteOrder(ctx, realArg.O)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceDeleteOrderArgs() interface{} {
	return order.NewOrderServiceDeleteOrderArgs()
}

func newOrderServiceDeleteOrderResult() interface{} {
	return order.NewOrderServiceDeleteOrderResult()
}

func getOrderStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceGetOrderStatusArgs)
	realResult := result.(*order.OrderServiceGetOrderStatusResult)
	success, err := handler.(order.OrderService).GetOrderStatus(ctx, realArg.O)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newOrderServiceGetOrderStatusArgs() interface{} {
	return order.NewOrderServiceGetOrderStatusArgs()
}

func newOrderServiceGetOrderStatusResult() interface{} {
	return order.NewOrderServiceGetOrderStatusResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateOrder(ctx context.Context, o *order.Order) (r *order.OrderResponse, err error) {
	var _args order.OrderServiceCreateOrderArgs
	_args.O = o
	var _result order.OrderServiceCreateOrderResult
	if err = p.c.Call(ctx, "CreateOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteOrder(ctx context.Context, o *order.Order) (r *order.OrderResponse, err error) {
	var _args order.OrderServiceDeleteOrderArgs
	_args.O = o
	var _result order.OrderServiceDeleteOrderResult
	if err = p.c.Call(ctx, "DeleteOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOrderStatus(ctx context.Context, o *order.Order) (r int64, err error) {
	var _args order.OrderServiceGetOrderStatusArgs
	_args.O = o
	var _result order.OrderServiceGetOrderStatusResult
	if err = p.c.Call(ctx, "GetOrderStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
